import type { AuditLogEntry } from "@/lib/types";

/** Mock audit trail (Phase 1). Scoped per role in `filterAuditLogsForCurrentUser`. */
export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "audit-1",
    occurredAt: "2026-04-26T14:22:00.000Z",
    actorUserId: "user-admin-1",
    subjectUserId: "user-emp-1",
    action: "user.role_viewed",
    title: "User profile viewed",
    description: "Admin opened employee record (mock).",
    category: "user",
  },
  {
    id: "audit-2",
    occurredAt: "2026-04-26T11:05:00.000Z",
    actorUserId: "user-mgr-1",
    subjectUserId: "user-emp-2",
    action: "leave.approved",
    title: "Leave request approved",
    description: "Manager approved leave for team member.",
    category: "leave",
  },
  {
    id: "audit-3",
    occurredAt: "2026-04-25T16:40:00.000Z",
    actorUserId: "user-emp-1",
    subjectUserId: "user-emp-1",
    action: "attendance.check_in",
    title: "Check-in recorded",
    description: "Employee checked in via web (mock).",
    category: "attendance",
  },
  {
    id: "audit-4",
    occurredAt: "2026-04-25T09:15:00.000Z",
    actorUserId: "user-admin-2",
    subjectUserId: "user-mgr-2",
    action: "team.updated",
    title: "Team membership updated",
    description: "Admin adjusted HR team roster (mock).",
    category: "team",
  },
  {
    id: "audit-5",
    occurredAt: "2026-04-24T13:00:00.000Z",
    actorUserId: "user-emp-2",
    subjectUserId: "user-emp-2",
    action: "task.status_changed",
    title: "Task moved to In progress",
    description: "Employee updated task board.",
    category: "task",
  },
  {
    id: "audit-6",
    occurredAt: "2026-04-24T08:30:00.000Z",
    actorUserId: "user-mgr-3",
    subjectUserId: "user-emp-4",
    action: "document.downloaded",
    title: "Document downloaded",
    description: "Manager exported sales doc (mock).",
    category: "document",
  },
  {
    id: "audit-7",
    occurredAt: "2026-04-23T17:50:00.000Z",
    actorUserId: "user-emp-5",
    subjectUserId: "user-emp-5",
    action: "leave.submitted",
    title: "Leave application submitted",
    description: "Employee submitted annual leave.",
    category: "leave",
  },
  {
    id: "audit-8",
    occurredAt: "2026-04-23T10:00:00.000Z",
    actorUserId: "user-admin-1",
    subjectUserId: "user-admin-1",
    action: "settings.policy_viewed",
    title: "Company settings viewed",
    description: "Admin reviewed organisation preferences.",
    category: "settings",
  },
  {
    id: "audit-9",
    occurredAt: "2026-04-22T15:20:00.000Z",
    actorUserId: "user-mgr-4",
    subjectUserId: "user-emp-1",
    action: "task.assigned",
    title: "Task reassigned",
    description: "Lead reassigned sprint item.",
    category: "task",
  },
  {
    id: "audit-10",
    occurredAt: "2026-04-22T07:45:00.000Z",
    actorUserId: "user-emp-3",
    subjectUserId: "user-emp-3",
    action: "auth.login",
    title: "Signed in",
    description: "Successful login (mock).",
    category: "auth",
  },
  {
    id: "audit-11",
    occurredAt: "2026-04-21T12:10:00.000Z",
    actorUserId: "user-mgr-1",
    subjectUserId: "user-mgr-1",
    action: "performance.report_exported",
    title: "Performance view opened",
    description: "Manager opened team performance (mock).",
    category: "settings",
  },
  {
    id: "audit-12",
    occurredAt: "2026-04-21T09:00:00.000Z",
    actorUserId: "user-admin-1",
    subjectUserId: "user-mgr-1",
    action: "user.deactivated",
    title: "Account flag reviewed",
    description: "Admin reviewed manager account status (mock).",
    category: "user",
  },
  {
    id: "audit-13",
    occurredAt: "2026-04-20T18:00:00.000Z",
    actorUserId: "user-emp-6",
    subjectUserId: "user-emp-6",
    action: "auth.logout",
    title: "Signed out",
    description: "Session ended.",
    category: "auth",
  },
  {
    id: "audit-14",
    occurredAt: "2026-04-20T11:30:00.000Z",
    actorUserId: "user-mgr-2",
    subjectUserId: "user-emp-3",
    action: "leave.rejected",
    title: "Leave request rejected",
    description: "HR manager rejected request with comment (mock).",
    category: "leave",
  },
  {
    id: "audit-15",
    occurredAt: "2026-04-19T14:00:00.000Z",
    actorUserId: "user-emp-4",
    subjectUserId: "user-emp-4",
    action: "document.uploaded",
    title: "Document uploaded",
    description: "Employee uploaded contract PDF (mock).",
    category: "document",
  },
  {
    id: "audit-16",
    occurredAt: "2026-04-19T08:00:00.000Z",
    actorUserId: "user-admin-2",
    subjectUserId: "user-emp-2",
    action: "attendance.rule_viewed",
    title: "Attendance rules viewed",
    description: "Admin opened policy sheet.",
    category: "attendance",
  },
  {
    id: "audit-17",
    occurredAt: "2026-04-18T16:15:00.000Z",
    actorUserId: "user-mgr-3",
    subjectUserId: "user-mgr-3",
    action: "shifts.template_viewed",
    title: "Shift template viewed",
    description: "Sales lead reviewed roster (mock).",
    category: "settings",
  },
  {
    id: "audit-18",
    occurredAt: "2026-04-18T10:45:00.000Z",
    actorUserId: "user-emp-1",
    subjectUserId: "user-mgr-1",
    action: "leave.comment_added",
    title: "Leave thread updated",
    description: "Employee replied on pending request.",
    category: "leave",
  },
  {
    id: "audit-19",
    occurredAt: "2026-04-17T13:20:00.000Z",
    actorUserId: "user-mgr-4",
    subjectUserId: "user-emp-2",
    action: "task.comment_added",
    title: "Comment on task",
    description: "Lead added review note.",
    category: "task",
  },
  {
    id: "audit-20",
    occurredAt: "2026-04-17T09:00:00.000Z",
    actorUserId: "user-admin-1",
    subjectUserId: "user-mgr-4",
    action: "user.permissions_viewed",
    title: "Directory lookup",
    description: "Admin viewed manager permissions (mock).",
    category: "user",
  },
  {
    id: "audit-21",
    occurredAt: "2026-04-16T15:00:00.000Z",
    actorUserId: "user-emp-2",
    subjectUserId: "user-emp-1",
    action: "task.mentioned",
    title: "@mention in task",
    description: "QA tagged engineer on defect.",
    category: "task",
  },
  {
    id: "audit-22",
    occurredAt: "2026-04-16T11:00:00.000Z",
    actorUserId: "user-mgr-1",
    subjectUserId: "user-emp-5",
    action: "attendance.note_added",
    title: "Attendance note",
    description: "Manager added note for late arrival (mock).",
    category: "attendance",
  },
  {
    id: "audit-23",
    occurredAt: "2026-04-15T14:30:00.000Z",
    actorUserId: "user-emp-5",
    subjectUserId: "user-emp-5",
    action: "settings.profile_updated",
    title: "Profile updated",
    description: "Employee changed phone number (mock).",
    category: "settings",
  },
  {
    id: "audit-24",
    occurredAt: "2026-04-15T08:00:00.000Z",
    actorUserId: "user-admin-2",
    subjectUserId: "user-admin-2",
    action: "auth.login",
    title: "Signed in",
    description: "Admin session started.",
    category: "auth",
  },
  {
    id: "audit-25",
    occurredAt: "2026-04-14T17:00:00.000Z",
    actorUserId: "user-mgr-2",
    subjectUserId: "user-emp-3",
    action: "document.category_viewed",
    title: "Categories reviewed",
    description: "HR manager browsed document types.",
    category: "document",
  },
];
