import type { User } from "@/lib/types";

export const mockUsers: User[] = [
  {
    id: "user-admin-1",
    email: "admin@company.com",
    firstName: "Alex",
    lastName: "Rivera",
    phone: "+1 555-0100",
    designation: "Head of HR",
    departmentId: "dept-hr",
    role: "admin",
    isActive: true,
  },
  {
    id: "user-admin-2",
    email: "sarah.admin@company.com",
    firstName: "Sarah",
    lastName: "Chen",
    phone: "+1 555-0101",
    designation: "Operations Director",
    departmentId: "dept-eng",
    role: "admin",
    isActive: true,
  },
  {
    id: "user-mgr-1",
    email: "manager@company.com",
    firstName: "Jordan",
    lastName: "Lee",
    phone: "+1 555-0200",
    designation: "Engineering Manager",
    departmentId: "dept-eng",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-mgr-2",
    email: "priya.m@company.com",
    firstName: "Priya",
    lastName: "Shah",
    phone: "+1 555-0201",
    designation: "HR Manager",
    departmentId: "dept-hr",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-mgr-3",
    email: "marcus.s@company.com",
    firstName: "Marcus",
    lastName: "Stone",
    phone: "+1 555-0202",
    designation: "Sales Lead",
    departmentId: "dept-sales",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-mgr-4",
    email: "elena.k@company.com",
    firstName: "Elena",
    lastName: "Kovacs",
    phone: "+1 555-0203",
    designation: "Team Lead",
    departmentId: "dept-eng",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-emp-1",
    email: "employee@company.com",
    firstName: "Sam",
    lastName: "Taylor",
    phone: "+1 555-0300",
    designation: "Software Engineer",
    departmentId: "dept-eng",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-emp-2",
    email: "jamie.l@company.com",
    firstName: "Jamie",
    lastName: "Lopez",
    phone: "+1 555-0301",
    designation: "QA Analyst",
    departmentId: "dept-eng",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-emp-3",
    email: "casey.w@company.com",
    firstName: "Casey",
    lastName: "Wong",
    phone: "+1 555-0302",
    designation: "HR Specialist",
    departmentId: "dept-hr",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-emp-4",
    email: "riley.b@company.com",
    firstName: "Riley",
    lastName: "Brooks",
    phone: "+1 555-0303",
    designation: "Account Executive",
    departmentId: "dept-sales",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-emp-5",
    email: "morgan.d@company.com",
    firstName: "Morgan",
    lastName: "Diaz",
    phone: "+1 555-0304",
    designation: "DevOps Engineer",
    departmentId: "dept-eng",
    role: "employee",
    isActive: true,
  },
  {
    id: "user-emp-6",
    email: "taylor.n@company.com",
    firstName: "Taylor",
    lastName: "Nguyen",
    phone: "+1 555-0305",
    designation: "Intern",
    departmentId: "dept-sales",
    role: "employee",
    isActive: false,
  },
];

export function getUserById(id: string) {
  return mockUsers.find((u) => u.id === id);
}

export function getUserByEmail(email: string) {
  return mockUsers.find((u) => u.email.toLowerCase() === email.toLowerCase());
}
